# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/leshiguang/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'lzbluetooth-mini-ui-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetactor/Layout/Classes/FBClassStrongLayout.mm",
#                   "layoutCache[currentClass] = ivars;",
#                   "layoutCache[(id)currentClass] = ivars;")
  pod "SDWebImage"
  pod "Masonry"
#  pod "CocoaDebug", "1.4.8"
  pod "YYModel"
  pod "LZBluetooth", "1.7.0"


  pod "IQKeyboardManager"
end

#target 'SwiftDemo' do
#  use_frameworks!
#  pod "LZBluetooth", "1.6.13"
##  pod 'LZBluetooth', :path => '../../lzbluetoothmini'
#  pod "SnapKit"
#end


