# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/leshiguang/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'lzbluetooth-mini-ui-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetactor/Layout/Classes/FBClassStrongLayout.mm",
#                   "layoutCache[currentClass] = ivars;",
#                   "layoutCache[(id)currentClass] = ivars;")
  pod "SDWebImage"
  pod "Masonry"
#  pod "CocoaDebug", "1.4.8"
  pod "YYModel"
  pod "LZShareKit"

#  pod "LZBluetooth", "1.6.13"
pod 'LZBluetooth'
pod 'LZBracelet'
pod 'LZScale'
pod 'LZBox'
pod 'LZBloodPressure', "1.0.3"
pod 'LZSkip'
pod 'LZCavosmart'
pod 'LZGlucose'

  pod "IQKeyboardManager"
end

#target 'SwiftDemo' do
#  use_frameworks!
#  pod 'LZBluetooth', "2.0.2"
#  pod 'LZBracelet', :path => '../../lzbluetoothmini'
#  pod 'LZScale'
#  pod 'LZBox'
#  pod 'LZBloodPressure', "1.0.1"
#  pod 'LZSkip'
##  pod 'LZBluetooth', :path => '../../lzbluetoothmini'
#  pod "SnapKit"
#end
