# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/leshiguang/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'lzbluetooth-mini-ui-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SDWebImage"
  pod "Masonry"
  pod "CocoaDebug" , "1.4.8"
  pod "YYModel"
  pod "LZBluetooth", "1.3.1"
  pod "IQKeyboardManager"
  

end
